### ISSUE TITLE
Multiple frameworks on base container

### ISSUE THREAD

**Issue by FoamScience** [FoamScience/openfoam-apptainer-packaging#8]
The current behavior of the ansible playbook is to:
1. build the MPI-based container
2. build the framework container on top of that 
3. build the project container on top of that

Building framework containers should allow for selection of multiple containers in the following way:
```
containers:
  basic:
    opencfd-openfoam:
      os:
        distro: ubuntu 
        version: 24.04
      mpi:
        implementation: openmpi
        version: 4.1.5 
      framework:
        - definition: com-openfoam
          version: 2312
        - definition: hpctoolkit
          version: 24.01.1
      coordination: script.sh
```
The objective is to build framework containers off of each other while executing `script.sh`  to adjust the framework build to work with the next/previous frameworks on the container
